2020-10-06T00:19:51.092346+00:00 app[web.1]: rule.bind(self)
2020-10-06T00:19:51.092347+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 730, in bind
2020-10-06T00:19:51.092879+00:00 app[web.1]: self.compile()
2020-10-06T00:19:51.092919+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 794, in compile
2020-10-06T00:19:51.093469+00:00 app[web.1]: self._build = self._compile_builder(False).__get__(self, None)
2020-10-06T00:19:51.093501+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 945, in _compile_builder
2020-10-06T00:19:51.094134+00:00 app[web.1]: code = compile(module, "<werkzeug routing>", "exec")
2020-10-06T00:19:51.094188+00:00 app[web.1]: TypeError: required field "type_ignores" missing from Module
2020-10-06T00:19:51.224784+00:00 heroku[web.1]: Process exited with status 1
2020-10-06T00:19:51.277655+00:00 heroku[web.1]: State changed from starting to crashed
2020-10-06T00:26:31.264144+00:00 heroku[web.1]: State changed from crashed to starting
2020-10-06T00:26:38.563509+00:00 heroku[web.1]: Starting process with command `python3 cem_primos.py`
2020-10-06T00:26:49.341675+00:00 app[web.1]: Error waiting for network: Resource temporarily unavailable
2020-10-06T00:28:39.040075+00:00 heroku[web.1]: State changed from starting to down
2020-10-06T01:08:53.000000+00:00 app[api]: Build started by user verronefilipe@gmail.com
2020-10-06T01:09:21.163155+00:00 app[api]: Deploy ee787b89 by user verronefilipe@gmail.com
2020-10-06T01:09:21.163155+00:00 app[api]: Release v6 created by user verronefilipe@gmail.com
2020-10-06T01:09:21.724490+00:00 heroku[web.1]: State changed from down to starting
2020-10-06T01:09:24.822705+00:00 heroku[web.1]: Starting process with command `python t8.py`
2020-10-06T01:09:27.480369+00:00 app[web.1]: * Serving Flask app "t8" (lazy loading)
2020-10-06T01:09:27.480461+00:00 app[web.1]: * Environment: production
2020-10-06T01:09:27.480538+00:00 app[web.1]: WARNING: Do not use the development server in a production environment.
2020-10-06T01:09:27.480604+00:00 app[web.1]: Use a production WSGI server instead.
2020-10-06T01:09:27.480658+00:00 app[web.1]: * Debug mode: off
2020-10-06T01:09:27.493137+00:00 app[web.1]: * Running on http://0.0.0.0:33018/ (Press CTRL+C to quit)
2020-10-06T01:09:29.000000+00:00 app[api]: Build succeeded
2020-10-06T01:09:29.127186+00:00 heroku[web.1]: State changed from starting to up
2020-10-06T01:10:35.060033+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=ec2bac03.herokuapp.com request_id=595b85ae-aa95-4d01-b3c0-b62a5139f30e fwd="191.162.76.34" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
2020-10-06T01:10:35.681848+00:00 app[web.1]: 10.43.233.181 - - [06/Oct/2020 01:10:35] "GET /favicon.ico HTTP/1.1" 404 -
2020-10-06T01:10:35.684347+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=ec2bac03.herokuapp.com request_id=f01eef13-1cee-4a8c-92ec-8b1d49bad37d fwd="191.162.76.34" dyno=web.1 connect=1ms service=137ms status=404 bytes=379 protocol=https
2020-10-06T01:11:12.605626+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=ec2bac03.herokuapp.com request_id=2de8a7be-767c-4fa7-8943-405d5c7a16c3 fwd="191.162.76.34" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2020-10-06T01:13:03.000000+00:00 app[api]: Build started by user verronefilipe@gmail.com
2020-10-06T01:13:26.184211+00:00 app[api]: Deploy 3ed056d6 by user verronefilipe@gmail.com
2020-10-06T01:13:26.184211+00:00 app[api]: Release v7 created by user verronefilipe@gmail.com
2020-10-06T01:13:26.504654+00:00 heroku[web.1]: Restarting
2020-10-06T01:13:26.523027+00:00 heroku[web.1]: State changed from up to starting
2020-10-06T01:13:27.893834+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-10-06T01:13:28.022357+00:00 heroku[web.1]: Process exited with status 143
2020-10-06T01:13:30.567263+00:00 heroku[web.1]: Starting process with command `python primos.py`
2020-10-06T01:13:34.000000+00:00 app[api]: Build succeeded
2020-10-06T01:13:35.333046+00:00 app[web.1]: * Serving Flask app "primos" (lazy loading)
2020-10-06T01:13:35.333084+00:00 app[web.1]: * Environment: production
2020-10-06T01:13:35.333135+00:00 app[web.1]: WARNING: Do not use the development server in a production environment.
2020-10-06T01:13:35.333215+00:00 app[web.1]: Use a production WSGI server instead.
2020-10-06T01:13:35.333285+00:00 app[web.1]: * Debug mode: off
2020-10-06T01:13:35.376269+00:00 app[web.1]: * Running on http://0.0.0.0:55441/ (Press CTRL+C to quit)
2020-10-06T01:13:35.856505+00:00 heroku[web.1]: State changed from starting to up
2020-10-06T01:27:24.000000+00:00 app[api]: Build started by user verronefilipe@gmail.com
2020-10-06T01:27:51.867192+00:00 app[api]: Deploy 562142e4 by user verronefilipe@gmail.com
2020-10-06T01:27:51.867192+00:00 app[api]: Release v8 created by user verronefilipe@gmail.com
2020-10-06T01:27:52.071565+00:00 heroku[web.1]: Restarting
2020-10-06T01:27:52.117438+00:00 heroku[web.1]: State changed from up to starting
2020-10-06T01:27:53.635862+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-10-06T01:27:53.747427+00:00 heroku[web.1]: Process exited with status 143
2020-10-06T01:27:55.246151+00:00 heroku[web.1]: Starting process with command `python primos.py`
2020-10-06T01:27:57.710978+00:00 app[web.1]: Traceback (most recent call last):
2020-10-06T01:27:57.710997+00:00 app[web.1]: File "primos.py", line 5, in <module>
2020-10-06T01:27:57.711117+00:00 app[web.1]: app = Flask(__name__)
2020-10-06T01:27:57.711133+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 556, in __init__
2020-10-06T01:27:57.711419+00:00 app[web.1]: self.add_url_rule(
2020-10-06T01:27:57.711420+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 64, in wrapper_func
2020-10-06T01:27:57.711538+00:00 app[web.1]: return f(self, *args, **kwargs)
2020-10-06T01:27:57.711563+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1214, in add_url_rule
2020-10-06T01:27:57.711954+00:00 app[web.1]: self.url_map.add(rule)
2020-10-06T01:27:57.711958+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 1386, in add
2020-10-06T01:27:57.712392+00:00 app[web.1]: rule.bind(self)
2020-10-06T01:27:57.712396+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 730, in bind
2020-10-06T01:27:57.712692+00:00 app[web.1]: self.compile()
2020-10-06T01:27:57.712696+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 794, in compile
2020-10-06T01:27:57.713013+00:00 app[web.1]: self._build = self._compile_builder(False).__get__(self, None)
2020-10-06T01:27:57.713014+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 945, in _compile_builder
2020-10-06T01:27:57.713423+00:00 app[web.1]: code = compile(module, "<werkzeug routing>", "exec")
2020-10-06T01:27:57.713433+00:00 app[web.1]: TypeError: required field "type_ignores" missing from Module
2020-10-06T01:27:57.804405+00:00 heroku[web.1]: Process exited with status 1
2020-10-06T01:27:57.844882+00:00 heroku[web.1]: State changed from starting to crashed
2020-10-06T01:27:57.847122+00:00 heroku[web.1]: State changed from crashed to starting
2020-10-06T01:28:00.000000+00:00 app[api]: Build succeeded
2020-10-06T01:28:01.927546+00:00 heroku[web.1]: Starting process with command `python primos.py`
2020-10-06T01:28:05.635766+00:00 app[web.1]: Traceback (most recent call last):
2020-10-06T01:28:05.635791+00:00 app[web.1]: File "primos.py", line 5, in <module>
2020-10-06T01:28:05.636075+00:00 app[web.1]: app = Flask(__name__)
2020-10-06T01:28:05.636081+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 556, in __init__
2020-10-06T01:28:05.636570+00:00 app[web.1]: self.add_url_rule(
2020-10-06T01:28:05.636598+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 64, in wrapper_func
2020-10-06T01:28:05.636805+00:00 app[web.1]: return f(self, *args, **kwargs)
2020-10-06T01:28:05.636833+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1214, in add_url_rule
2020-10-06T01:28:05.637596+00:00 app[web.1]: self.url_map.add(rule)
2020-10-06T01:28:05.637620+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 1386, in add
2020-10-06T01:28:05.638450+00:00 app[web.1]: rule.bind(self)
2020-10-06T01:28:05.638482+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 730, in bind
2020-10-06T01:28:05.639026+00:00 app[web.1]: self.compile()
2020-10-06T01:28:05.639052+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 794, in compile
2020-10-06T01:28:05.639617+00:00 app[web.1]: self._build = self._compile_builder(False).__get__(self, None)
2020-10-06T01:28:05.639651+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/werkzeug/routing.py", line 945, in _compile_builder
2020-10-06T01:28:05.640350+00:00 app[web.1]: code = compile(module, "<werkzeug routing>", "exec")
2020-10-06T01:28:05.640421+00:00 app[web.1]: TypeError: required field "type_ignores" missing from Module
2020-10-06T01:28:05.752528+00:00 heroku[web.1]: Process exited with status 1
2020-10-06T01:28:05.791197+00:00 heroku[web.1]: State changed from starting to crashed
2020-10-06T01:35:07.197204+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ec2bac03.herokuapp.com request_id=f3b23073-d52d-4cc5-8bc8-27c9dc25f0e2 fwd="191.162.76.34" dyno= connect= service= status=503 bytes= protocol=https
2020-10-06T01:35:29.682342+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ec2bac03.herokuapp.com request_id=1a2b1055-464f-46b3-9e86-4a594d8ddc60 fwd="191.162.76.34" dyno= connect= service= status=503 bytes= protocol=https
